version: '3.1'

services:
  database:
    image: postgres:14.2-alpine
    platform: linux/x86_64
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postres_data:/var/lib/postgresql/data

volumes:
  postres_data:
