type Freight {
  freight: Float
}

input SimulateFreightItems {
  item_id: String!
  quantity: Int!
}

type Query {
  simulateFreight(
    from_cep: String!
    to_cep: String!
    items: [SimulateFreightItems!]!
  ): Freight!
}
